#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Anoushka Bakshi
# Course: Open Source Software
# Purpose: Interactive script to generate a personalized FOSS manifesto file.

# --- Concept: Aliases (Unit 5)
# Note: In a live shell, one might use: alias today='date +"%d %B %Y"'
# For this script's reliability across different shells, we use a variable.
DATE_STRING=$(date '+%d %B %Y')
USER_ID=$(whoami)
OUTPUT_FILE="manifesto_${USER_ID}.txt"

echo "======================================"
echo "   Open Source Manifesto Generator    "
echo "======================================"
echo "Please provide your perspective on FOSS:"
echo ""

# --- Gather user input interactively using read -p
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

echo ""
echo "Generating your manifesto and saving to $OUTPUT_FILE..."

# --- Grouping commands using { ... } and redirecting output to a file
# This demonstrates block redirection (>) using a dynamically named file
{
    echo "======================================"
    echo "       MY OPEN SOURCE MANIFESTO       "
    echo "======================================"
    echo "Generated by: $USER_ID on $DATE_STRING"
    echo ""
    echo "Every day, I rely on tools like $TOOL, which were"
    echo "built by communities who decided to share their"
    echo "knowledge rather than lock it away."
    echo ""
    echo "To me, freedom means '$FREEDOM'. This is exactly what"
    echo "the GPL v2 license protects in the Linux Kernel—it"
    echo "ensures that the community's work remains accessible to all."
    echo ""
    echo "If I had the resources, I would build $BUILD"
    echo "and release it openly. We stand on the shoulders of giants,"
    echo "and contributing back is how we build the future."
    echo "--------------------------------------"
} > "$OUTPUT_FILE"

echo "Success!"
echo ""
echo "--- Content of $OUTPUT_FILE ---"
# Display the file content to the terminal using cat
cat "$OUTPUT_FILE"
echo ""
echo "======================================"